#ifndef TEAM35_CODE35_SRC_SPA_SRC_QPS_QUERY_PARSER_HELPER_H_
#define TEAM35_CODE35_SRC_SPA_SRC_QPS_QUERY_PARSER_HELPER_H_

#define WITHENT_KEYWORD "WithEnt"
#define WITHNUM_KEYWORD "WithNum"
#define USESS_KEYWORD "UsesS"
#define MODIFIESS_KEYWORD "ModifiesS"
#define USESP_KEYWORD "UsesP"
#define MODIFIESP_KEYWORD "ModifiesP"
#define PARENT_KEYWORD "Parent"
#define FOLLOW_KEYWORD "Follows"
#define PARENTSTAR_KEYWORD "Parent*"
#define FOLLOWSTAR_KEYWORD "Follows*"
#define CALLS_KEYWORD "Calls"
#define CALLSSTAR_KEYWORD "Calls*"
#define NEXT_KEYWORD "Next"
#define NEXTSTAR_KEYWORD "Next*"
#define AFFECTS_KEYWORD "Affects"
#define AFFECTSSTAR_KEYWORD "Affects*"

#define PROCNAME_KEYWORD "procName"
#define VARNAME_KEYWORD "varName"
#define VALUE_KEYWORD "value"
#define STMT_KEYWORD "stmt"

#define USES_MODIFIES_S_APPEND "S"
#define USES_MODIFIES_P_APPEND "P"

#define PERIOD "."

#endif  // TEAM35_CODE35_SRC_SPA_SRC_QPS_QUERY_PARSER_HELPER_H_
