name: CI for Cmake Project - Windows
run-name: ${{ github.actor }} is running Windows CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 23 * * *"

env:
  BUILD_TYPE: Release

jobs:
  lint:
    name: Windows Lint
    runs-on: windows-latest
    timeout-minutes: 3
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run cpplint linter to check code styles
        working-directory: Team35/Code35
        run: |
          pip install cpplint; bash ./linter.sh

  build:
    name: Windows Build
    runs-on: windows-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        shell: bash
        working-directory: Team35/Code35
        run: |
          mkdir build
          cd build
          cmake -A x64 ..
          cmake --build . --target unit_testing --config $BUILD_TYPE
          cmake --build . --target integration_testing --config $BUILD_TYPE
          cmake --build . --target autotester --config $BUILD_TYPE
          cd ../..

      - name: Run Unit Test
        shell: bash
        working-directory: Team35/Code35/build
        run: ./src/unit_testing/Release/unit_testing.exe
